-- V1: the four tables from the handout (section 5.1).
-- Flyway runs this file once and records it in flyway_schema_history.
-- Never edit it after it has been applied; add V2__... instead.

CREATE TABLE groups (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       varchar(80) NOT NULL,
    join_code  varchar(8)  NOT NULL,
    status     varchar(16) NOT NULL DEFAULT 'LOBBY',
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT groups_join_code_key UNIQUE (join_code),
    CONSTRAINT groups_status_check CHECK (status IN ('LOBBY', 'WATCHING', 'DONE'))
);

CREATE TABLE members (
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id bigint      NOT NULL REFERENCES groups (id) ON DELETE CASCADE,
    nickname varchar(30) NOT NULL,
    token    varchar(64) NOT NULL,
    CONSTRAINT members_token_key UNIQUE (token)
);

-- Unique nickname per group, ignoring case, so "Sam" and "sam" cannot both join.
CREATE UNIQUE INDEX members_group_nickname_key ON members (group_id, lower(nickname));

CREATE TABLE picks (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id     bigint       NOT NULL REFERENCES groups (id) ON DELETE CASCADE,
    member_id    bigint       NOT NULL REFERENCES members (id) ON DELETE CASCADE,
    source       varchar(16)  NOT NULL,
    tmdb_id      bigint,
    title        varchar(200) NOT NULL,
    release_year integer      NOT NULL,
    poster_url   varchar(500),
    watch_order  integer,
    vetoed       boolean      NOT NULL DEFAULT false,
    -- A TMDB pick must carry a tmdb_id; a manual pick must not.
    CONSTRAINT picks_source_tmdb_id_check CHECK (
        (source = 'TMDB' AND tmdb_id IS NOT NULL)
        OR (source = 'MANUAL' AND tmdb_id IS NULL)
    ),
    -- NULLs never collide, so this only bites once the group has started.
    CONSTRAINT picks_group_watch_order_key UNIQUE (group_id, watch_order)
);

-- At most one live pick per member. A partial index skips vetoed rows,
-- so a member whose pick was vetoed can pick again.
CREATE UNIQUE INDEX picks_one_live_pick_per_member ON picks (group_id, member_id) WHERE NOT vetoed;

CREATE TABLE ratings (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pick_id    bigint  NOT NULL REFERENCES picks (id) ON DELETE CASCADE,
    member_id  bigint  NOT NULL REFERENCES members (id) ON DELETE CASCADE,
    scariness  integer NOT NULL CHECK (scariness BETWEEN 1 AND 10),
    atmosphere integer NOT NULL CHECK (atmosphere BETWEEN 1 AND 10),
    story      integer NOT NULL CHECK (story BETWEEN 1 AND 10),
    acting     integer NOT NULL CHECK (acting BETWEEN 1 AND 10),
    enjoyment  integer NOT NULL CHECK (enjoyment BETWEEN 1 AND 10),
    CONSTRAINT ratings_pick_member_key UNIQUE (pick_id, member_id)
);

-- Postgres indexes primary keys and unique constraints, but not foreign keys.
CREATE INDEX picks_member_id_idx ON picks (member_id);
CREATE INDEX ratings_member_id_idx ON ratings (member_id);
