-- V2: "I've seen it" flags. One row per member per pick; when enough members have
-- flagged a pick, the application marks it vetoed and its picker chooses again.
CREATE TABLE seen_flags (
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pick_id   bigint NOT NULL REFERENCES picks (id) ON DELETE CASCADE,
    member_id bigint NOT NULL REFERENCES members (id) ON DELETE CASCADE,
    -- A member counts once per pick, however many times they tap.
    CONSTRAINT seen_flags_pick_member_key UNIQUE (pick_id, member_id)
);

CREATE INDEX seen_flags_member_id_idx ON seen_flags (member_id);
