-- V4: golden tickets. After rating, each member gives one ticket to another member.

-- A new stage between WATCHING and DONE, while tickets are being handed out.
ALTER TABLE groups DROP CONSTRAINT groups_status_check;
ALTER TABLE groups ADD CONSTRAINT groups_status_check
    CHECK (status IN ('LOBBY', 'WATCHING', 'TICKETS', 'DONE'));

CREATE TABLE golden_tickets (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    giver_id     bigint NOT NULL REFERENCES members (id) ON DELETE CASCADE,
    recipient_id bigint NOT NULL REFERENCES members (id) ON DELETE CASCADE,
    -- One ticket per member.
    CONSTRAINT golden_tickets_giver_key UNIQUE (giver_id),
    -- Nobody can give the ticket to themselves.
    CONSTRAINT golden_tickets_not_self_check CHECK (giver_id <> recipient_id)
);

CREATE INDEX golden_tickets_recipient_id_idx ON golden_tickets (recipient_id);
